update postrm script

diff --git a/packages/debian/src/postrm b/packages/debian/src/postrm
--- a/packages/debian/src/postrm
+++ b/packages/debian/src/postrm
@@ -1,32 +1,30 @@
-#!/bin/sh
-# prerm script for wyliodrin-server
+# postrm script for wyliodrin-app-server
 #
 # see: dh_installdeb(1)
 
 set -e
 
 # summary of how this script can be called:
-#        * <prerm> `remove'
-#        * <old-prerm> `upgrade' <new-version>
-#        * <new-prerm> `failed-upgrade' <old-version>
-#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
-#        * <deconfigured's-prerm> `deconfigure' `in-favour'
-#          <package-being-installed> <version> `removing'
-#          <conflicting-package> <version>
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
-    remove|upgrade|deconfigure)
-	/bin/rm /etc/disable_getty_GS0
-    ;;
-
-    failed-upgrade)
+    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+  /bin/rm /etc/disable_getty_GS0
     ;;
 
     *)
-        echo "prerm called with unknown argument \`$1'" >&2
+        echo "postrm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
